const LS_MATCHES="apostas3_matches_v1",LS_BETS="apostas3_bets_v1";
const mainMarkets=["BTTS Sim","BTTS Não","Over 1.5","Under 2.5","Over 2.5","Under 3.5","Casa ML","Empate","Fora ML","Casa DNB","Fora DNB","Casa AH -0.5","Casa AH +0","Fora AH +0.5","Fora AH +0"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(v){return "R$ "+Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}
function pct(v){return (Number(v||0)*100).toFixed(2)+"%"} function odd(v){return Number(v||0).toFixed(2)} function today(){return new Date().toISOString().slice(0,10)}
function toast(msg){const t=$("#toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2500)}
function getMatches(){return JSON.parse(localStorage.getItem(LS_MATCHES)||"[]")} function setMatches(x){localStorage.setItem(LS_MATCHES,JSON.stringify(x))}
function getBets(){return JSON.parse(localStorage.getItem(LS_BETS)||"[]")} function setBets(x){localStorage.setItem(LS_BETS,JSON.stringify(x))}
function seedData(){const s=[["2026-06-01","Série B","Vila Nova","Time A",2,1],["2026-05-25","Série B","Vila Nova","Time B",1,0],["2026-05-18","Série B","Vila Nova","Time C",1,1],["2026-05-11","Série B","Vila Nova","Time D",0,0],["2026-05-04","Série B","Vila Nova","Time E",2,0],["2026-04-27","Série B","Vila Nova","Time K",3,1],["2026-04-20","Série B","Vila Nova","Time L",0,1],["2026-04-13","Série B","Vila Nova","Time M",1,1],["2026-04-06","Série B","Vila Nova","Time N",2,2],["2026-03-30","Série B","Vila Nova","Time O",1,0],["2026-06-02","Série B","Time F","Novorizontino",1,1],["2026-05-26","Série B","Time G","Novorizontino",0,2],["2026-05-19","Série B","Time H","Novorizontino",2,1],["2026-05-12","Série B","Time I","Novorizontino",1,0],["2026-05-05","Série B","Time J","Novorizontino",1,1],["2026-04-28","Série B","Time P","Novorizontino",0,0],["2026-04-21","Série B","Time Q","Novorizontino",2,2],["2026-04-14","Série B","Time R","Novorizontino",1,2],["2026-04-07","Série B","Time S","Novorizontino",3,1],["2026-03-31","Série B","Time T","Novorizontino",0,1],["2026-06-01","Série A","Palmeiras","Time Z",2,0],["2026-05-25","Série A","Palmeiras","Time Y",3,1],["2026-05-18","Série A","Time X","Flamengo",1,2],["2026-05-11","Série A","Time W","Flamengo",0,1]].map((r,i)=>({id:Date.now()+i,date:r[0],league:r[1],home:r[2],away:r[3],hg:r[4],ag:r[5]}));setMatches([...getMatches(),...s]);refreshAll();toast("Base carregada")}
function poisson(k,lam){if(lam<=0)return 0;let f=1;for(let i=2;i<=k;i++)f*=i;return Math.exp(-lam)*Math.pow(lam,k)/f}
function scoreMatrix(lh,la,max=8){let rows=[];for(let h=0;h<=max;h++)for(let a=0;a<=max;a++)rows.push({h,a,p:poisson(h,lh)*poisson(a,la)});let s=rows.reduce((x,r)=>x+r.p,0);return rows.map(r=>({...r,p:s?r.p/s:0}))}
function calcMarkets(lh,la){const m=scoreMatrix(lh,la),sum=fn=>m.filter(fn).reduce((a,r)=>a+r.p,0),rows=[];const ph=sum(r=>r.h>r.a),pd=sum(r=>r.h===r.a),pa=sum(r=>r.h<r.a),bt=sum(r=>r.h>0&&r.a>0);rows.push({market:"Casa ML",prob:ph},{market:"Empate",prob:pd},{market:"Fora ML",prob:pa},{market:"Casa DNB",prob:ph+.5*pd},{market:"Fora DNB",prob:pa+.5*pd},{market:"BTTS Sim",prob:bt},{market:"BTTS Não",prob:1-bt});[.5,1.5,2.5,3.5,4.5].forEach(l=>{let o=sum(r=>r.h+r.a>l);rows.push({market:`Over ${l}`,prob:o},{market:`Under ${l}`,prob:1-o})});[-1.5,-1,-.5,0,.5,1,1.5].forEach(l=>{let hw=sum(r=>r.h-r.a+l>0),hp=sum(r=>r.h-r.a+l===0),aw=sum(r=>r.a-r.h+l>0),ap=sum(r=>r.a-r.h+l===0);rows.push({market:`Casa AH ${l>=0?"+":""}${l}`,prob:hw+.5*hp},{market:`Fora AH ${l>=0?"+":""}${l}`,prob:aw+.5*ap})});return rows.map(r=>({...r,fair:r.prob?1/r.prob:null})).sort((a,b)=>b.prob-a.prob)}
function summarizeTeam(team,league,type){let rows=getMatches().filter(m=>m.league.toLowerCase()===league.toLowerCase()).filter(m=>type==="home"?m.home.toLowerCase()===team.toLowerCase():m.away.toLowerCase()===team.toLowerCase()).slice(0,10);if(!rows.length)return{games:0,gf:0,ga:0,btts:0,over25:0};let gf=rows.reduce((a,r)=>a+(type==="home"?r.hg:r.ag),0)/rows.length,ga=rows.reduce((a,r)=>a+(type==="home"?r.ag:r.hg),0)/rows.length,btts=rows.filter(r=>r.hg>0&&r.ag>0).length/rows.length,over25=rows.filter(r=>r.hg+r.ag>2.5).length/rows.length;return{games:rows.length,gf,ga,btts,over25}}
function estimateLambdas(home,away,league,adjH=0,adjA=0){let hs=summarizeTeam(home,league,"home"),as=summarizeTeam(away,league,"away"),lh=1.25,la=1.05;if(hs.games&&as.games){lh=hs.gf*.55+as.ga*.45;la=as.gf*.55+hs.ga*.45}return{lh:Math.max(.1,Math.min(4,lh+Number(adjH||0))),la:Math.max(.1,Math.min(4,la+Number(adjA||0))),hs,as}}
function kelly(prob,oddv){if(oddv<=1)return 0;let b=oddv-1;return Math.max(0,(b*prob-(1-prob))/b)}
function compareOdds(markets,oddsRows,bankroll,minEdge){return oddsRows.map(o=>{let m=markets.find(x=>x.market===o.market);if(!m)return null;let edge=o.odd/m.fair-1,ev=m.prob*o.odd-1,k=kelly(m.prob,o.odd),stake=Math.min(bankroll*.03,k*.25*bankroll);let decision="🔴 Passar",cls="red";if(edge>=minEdge&&ev>0){decision="🟢 ENTRADA";cls="green"}else if(ev>0){decision="🟡 Valor leve";cls="yellow"}return{...m,odd:o.odd,edge,ev,kelly:k,stake,decision,cls}}).filter(Boolean).sort((a,b)=>b.edge-a.edge)}
function uniqueTeams(league){return [...new Set(getMatches().filter(m=>m.league.toLowerCase()===league.toLowerCase()).flatMap(m=>[m.home,m.away]))].sort()}
function refreshTeams(){let league=$("#leagueInput").value.trim(),teams=uniqueTeams(league),h=$("#homeSelect"),a=$("#awaySelect");h.innerHTML="";a.innerHTML="";teams.forEach(t=>{h.add(new Option(t,t));a.add(new Option(t,t))});if(teams.length>1)a.selectedIndex=1}
function renderOddsGrid(){let g=$("#oddsGrid");g.innerHTML="";mainMarkets.forEach(m=>{let l=document.createElement("label"),i=document.createElement("input");l.textContent=m;i.type="number";i.min=0;i.max=50;i.step=.01;i.value=0;i.dataset.market=m;l.appendChild(i);g.appendChild(l)})}
let lastRadar=[];
function runScanner(){let league=$("#leagueInput").value.trim(),home=$("#homeSelect").value,away=$("#awaySelect").value,bankroll=Number($("#bankrollInput").value||1000),minEdge=Number($("#edgeInput").value||.06),adjH=Number($("#homeAdjInput").value||0),adjA=Number($("#awayAdjInput").value||0);let e=estimateLambdas(home,away,league,adjH,adjA);$("#lambdaHome").textContent=odd(e.lh);$("#lambdaAway").textContent=odd(e.la);$("#homeGames").textContent=e.hs.games;$("#awayGames").textContent=e.as.games;$("#homeBtts").textContent=pct(e.hs.btts);$("#awayBtts").textContent=pct(e.as.btts);let markets=calcMarkets(e.lh,e.la);renderAllMarkets(markets);let oddsRows=$$("#oddsGrid input").filter(i=>Number(i.value)>0).map(i=>({market:i.dataset.market,odd:Number(i.value)}));let radar=compareOdds(markets,oddsRows,bankroll,minEdge),f=$("#decisionFilter").value;if(f==="entrada")radar=radar.filter(r=>r.decision.includes("ENTRADA"));if(f==="valor")radar=radar.filter(r=>r.ev>0);lastRadar=radar.map(r=>({...r,league,game:`${home} x ${away}`}));renderRadar()}
function renderAllMarkets(markets){let tb=$("#allMarketsTable tbody");tb.innerHTML="";markets.forEach(r=>tb.insertAdjacentHTML("beforeend",`<tr><td>${r.market}</td><td>${pct(r.prob)}</td><td>${odd(r.fair)}</td></tr>`))}
function renderRadar(){let tb=$("#radarTable tbody");tb.innerHTML="";if(!lastRadar.length){tb.innerHTML='<tr><td colspan="10">Digite odds e clique em calcular.</td></tr>';return}lastRadar.forEach((r,i)=>tb.insertAdjacentHTML("beforeend",`<tr><td>${r.market}</td><td>${pct(r.prob)}</td><td>${odd(r.fair)}</td><td>${odd(r.odd)}</td><td>${pct(r.edge)}</td><td>${pct(r.ev)}</td><td>${pct(r.kelly)}</td><td>${money(r.stake)}</td><td><span class="badge ${r.cls}">${r.decision}</span></td><td><button onclick="saveRadarBet(${i})">Salvar</button></td></tr>`))}
function saveRadarBet(i){let r=lastRadar[i],bets=getBets();bets.unshift({id:Date.now(),date:today(),league:r.league,game:r.game,market:r.market,odd:r.odd,fair:r.fair,prob:r.prob,edge:r.edge,ev:r.ev,kelly:r.kelly,stake:Math.max(1,Number(r.stake||0)),result:"pending",profit:0});setBets(bets);refreshAll();toast("Aposta salva")}
function addMatch(){let m={id:Date.now(),date:$("#matchDate").value||today(),league:$("#matchLeague").value.trim(),home:$("#matchHome").value.trim(),away:$("#matchAway").value.trim(),hg:Number($("#matchHG").value||0),ag:Number($("#matchAG").value||0)};if(!m.league||!m.home||!m.away){toast("Preencha liga e times");return}setMatches([m,...getMatches()]);refreshAll();toast("Jogo salvo")}
function renderMatches(){let tb=$("#matchesTable tbody");tb.innerHTML="";getMatches().forEach(m=>tb.insertAdjacentHTML("beforeend",`<tr><td>${m.date}</td><td>${m.league}</td><td>${m.home}</td><td>${m.away}</td><td>${m.hg}-${m.ag}</td><td><button class="danger" onclick="deleteMatch(${m.id})">Excluir</button></td></tr>`))}
function deleteMatch(id){setMatches(getMatches().filter(m=>m.id!==id));refreshAll()}
function metrics(){let s=getBets().filter(b=>["win","half_win","push","half_loss","loss"].includes(b.result)),stake=s.reduce((a,b)=>a+Number(b.stake||0),0),profit=s.reduce((a,b)=>a+Number(b.profit||0),0),wins=s.filter(b=>["win","half_win"].includes(b.result)).length;return{bets:s.length,stake,profit,roi:stake?profit/stake:0,hit:s.length?wins/s.length:0}}
function settleProfit(b){if(b.result==="win")return b.stake*(b.odd-1);if(b.result==="half_win")return b.stake/2*(b.odd-1);if(b.result==="push")return 0;if(b.result==="half_loss")return -b.stake/2;if(b.result==="loss")return -b.stake;return 0}
function updateBetResult(id,result){setBets(getBets().map(b=>{if(b.id===id){b.result=result;b.profit=settleProfit(b)}return b}));refreshAll()}
function renderBets(){let m=metrics();$("#mBets").textContent=m.bets;$("#mStake").textContent=money(m.stake);$("#mProfit").textContent=money(m.profit);$("#mRoi").textContent=pct(m.roi);$("#mHit").textContent=pct(m.hit);let tb=$("#betsTable tbody");tb.innerHTML="";getBets().forEach(b=>tb.insertAdjacentHTML("beforeend",`<tr><td>${b.id}</td><td>${b.date}</td><td>${b.league}</td><td>${b.game}</td><td>${b.market}</td><td>${odd(b.odd)}</td><td>${odd(b.fair)}</td><td>${pct(b.ev)}</td><td>${money(b.stake)}</td><td><select onchange="updateBetResult(${b.id},this.value)">${["pending","win","half_win","push","half_loss","loss"].map(x=>`<option ${b.result===x?"selected":""}>${x}</option>`).join("")}</select></td><td>${money(b.profit)}</td><td><button class="danger" onclick="deleteBet(${b.id})">Excluir</button></td></tr>`))}
function deleteBet(id){setBets(getBets().filter(b=>b.id!==id));refreshAll()}
function groupStats(key){let settled=getBets().filter(b=>["win","half_win","push","half_loss","loss"].includes(b.result)),map={};settled.forEach(b=>{let k=b[key]||"-";if(!map[k])map[k]={name:k,bets:0,stake:0,profit:0,wins:0};map[k].bets++;map[k].stake+=Number(b.stake||0);map[k].profit+=Number(b.profit||0);if(["win","half_win"].includes(b.result))map[k].wins++});return Object.values(map).map(x=>({...x,roi:x.stake?x.profit/x.stake:0,hit:x.bets?x.wins/x.bets:0})).sort((a,b)=>b.profit-a.profit)}
function renderDashboard(){let market=groupStats("market"),league=groupStats("league"),bets=getBets().filter(b=>["win","half_win","push","half_loss","loss"].includes(b.result));$("#bestMarket").textContent=market[0]?.name||"-";$("#worstMarket").textContent=market[market.length-1]?.name||"-";$("#biggestWin").textContent=money(Math.max(0,...bets.map(b=>b.profit||0)));$("#biggestLoss").textContent=money(Math.min(0,...bets.map(b=>b.profit||0)));renderStatsTable("#marketStatsTable tbody",market);renderStatsTable("#leagueStatsTable tbody",league)}
function renderStatsTable(sel,rows){let tb=$(sel);tb.innerHTML="";rows.forEach(r=>tb.insertAdjacentHTML("beforeend",`<tr><td>${r.name}</td><td>${r.bets}</td><td>${money(r.stake)}</td><td>${money(r.profit)}</td><td>${pct(r.roi)}</td><td>${pct(r.hit)}</td></tr>`))}
function runBacktest(){let league=$("#btLeague").value.trim(),market=$("#btMarket").value,th=Number($("#btThreshold").value||.6),rows=getMatches().filter(m=>m.league.toLowerCase()===league.toLowerCase()).sort((a,b)=>a.date.localeCompare(b.date)),out=[];rows.forEach(m=>{let est=estimateLambdas(m.home,m.away,m.league),prob=calcMarkets(est.lh,est.la).find(x=>x.market===market)?.prob||0,hit=false;if(market==="BTTS Sim")hit=m.hg>0&&m.ag>0;else if(market.startsWith("Over"))hit=m.hg+m.ag>Number(market.split(" ")[1]);else if(market==="Casa ML")hit=m.hg>m.ag;else if(market==="Fora ML")hit=m.ag>m.hg;let entry=prob>=th;out.push({date:m.date,game:`${m.home} x ${m.away}`,score:`${m.hg}-${m.ag}`,prob,entry,green:entry?hit:null})});let tb=$("#backtestTable tbody");tb.innerHTML="";out.forEach(r=>tb.insertAdjacentHTML("beforeend",`<tr><td>${r.date}</td><td>${r.game}</td><td>${r.score}</td><td>${pct(r.prob)}</td><td>${r.entry?"Sim":"Não"}</td><td>${r.green===null?"-":r.green?"Green":"Red"}</td></tr>`));let entries=out.filter(r=>r.entry),greens=entries.filter(r=>r.green).length;$("#btEntries").textContent=entries.length;$("#btGreens").textContent=greens;$("#btHit").textContent=entries.length?pct(greens/entries.length):"0%"}
function exportData(){let blob=new Blob([JSON.stringify({matches:getMatches(),bets:getBets(),exportedAt:new Date().toISOString()},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="apostas-3-backup.json";a.click()}
function importData(file){let r=new FileReader();r.onload=e=>{let d=JSON.parse(e.target.result);if(d.matches)setMatches(d.matches);if(d.bets)setBets(d.bets);refreshAll();toast("Dados importados")};r.readAsText(file)}
function downloadCsvTemplate(){let blob=new Blob(["data,liga,mandante,visitante,gols_mandante,gols_visitante\n2026-06-01,Série B,Vila Nova,Novorizontino,1,1\n"],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="modelo_jogos.csv";a.click()}
function importCsv(file){let r=new FileReader();r.onload=e=>{let lines=e.target.result.split(/\r?\n/).filter(Boolean),header=lines.shift().split(",").map(x=>x.trim().toLowerCase()),idx=n=>header.indexOf(n),rows=lines.map((line,i)=>{let c=line.split(",");return{id:Date.now()+i,date:c[idx("data")]||c[idx("match_date")]||today(),league:c[idx("liga")]||c[idx("league")]||"Sem liga",home:c[idx("mandante")]||c[idx("home_team")]||"",away:c[idx("visitante")]||c[idx("away_team")]||"",hg:Number(c[idx("gols_mandante")]||c[idx("home_goals")]||0),ag:Number(c[idx("gols_visitante")]||c[idx("away_goals")]||0)}}).filter(r=>r.home&&r.away);setMatches([...getMatches(),...rows]);refreshAll();toast(`${rows.length} jogos importados`)};r.readAsText(file)}
function refreshAll(){refreshTeams();renderMatches();renderBets();renderDashboard()}
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(b=>b.classList.remove('active'));$$('.panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab).classList.add('active')}));
$("#seedBtn").onclick=seedData;$("#scanBtn").onclick=runScanner;$("#addMatchBtn").onclick=addMatch;$("#clearMatchesBtn").onclick=()=>{if(confirm("Limpar todos os jogos?")){setMatches([]);refreshAll()}};$("#clearBetsBtn").onclick=()=>{if(confirm("Limpar histórico?")){setBets([]);refreshAll()}};$("#resetAllBtn").onclick=()=>{if(confirm("Resetar tudo?")){localStorage.removeItem(LS_MATCHES);localStorage.removeItem(LS_BETS);refreshAll()}};$("#exportBtn").onclick=exportData;$("#importFile").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$("#downloadCsvTemplateBtn").onclick=downloadCsvTemplate;$("#csvFile").onchange=e=>e.target.files[0]&&importCsv(e.target.files[0]);$("#runBacktestBtn").onclick=runBacktest;$("#leagueInput").addEventListener("change",refreshTeams);$("#matchDate").value=today();renderOddsGrid();refreshAll();renderRadar();
